### PR TITLE
Templating

### PR DESCRIPTION
**Pull request by Leohemmingsson**
# Description
Started to structure the project a little. The routes exist in each "version" folder, and all of the exposed routes (in init) are automatically added.

 * Added datatypes (items, users)
 *  Added route templating (items, orders, users)

### CODE REVIEW

**Comment by SuadHus** [comment]
looks good

**Comment by SuadHus** [comment]
CLOZED

**Comment by SuadHus** [comment]
haram

**Comment by SuadHus** [comment]
haram

**Comment by LinusHakegard** [comment]
good structure

**Pull request merged**
